config/routes.rb
Penpencilruler::Application.routes.draw do

  get '/terms' => 'pages#terms'
  get '/privacy' => 'pages#privacy'
  get '/copyright' => 'pages#copyright'
  get '/feedback' => 'pages#feedback'
  get '/cookies' => 'pages#cookies'
  get '/suspended' => 'pages#suspended', as: 'suspended'

  devise_for :users, controllers: { registrations: "users/registrations"}

  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    resource :registration,
    only: [:new, :create, :edit, :update],
    path: 'users',
    path_names: { new: 'sign_up' },
    controller: 'devise/registrations',
    as: :user_registration do
      get :cancel
    end
  end

  resources :search

  resources :subjects do
    resources :topics do
      resources :notes
    end
  end

  get '/admin' => 'admin#index', as: 'admin'
  get '/admin/users/search/:search' => 'admin#users', as: 'admin_userssearch'
  get '/admin/users(/:id)' => 'admin#users', as: 'admin_users'
  get '/admin/become/:id' => 'admin#become', as: 'admin_become'
  get '/admin/suspend/:id' => 'admin#suspend', as: 'admin_suspend'
  get '/admin/unsuspend/:id' => 'admin#unsuspend', as: 'admin_unsuspend'
  get '/admin/allowdeletion/:id' => 'admin#allowdeletion', as: 'admin_allowdeletion'
  get '/admin/preventdeletion/:id' => 'admin#preventdeletion', as: 'admin_preventdeletion'

  get '/admin/support' => redirect('https://secure.helpscout.net'), as: 'admin_support'
  get '/admin/newrelic' => redirect('https://rpm.newrelic.com'), as: 'admin_newrelic'
  get '/admin/postmarkapp' => redirect('https://postmarkapp.com'), as: 'admin_postmarkapp'

  root :to => 'pages#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :name, :subject_id
  has_many :notes, dependent: :delete_all
  belongs_to :subject
  belongs_to :user
  validates :name, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :require_login
  
  def index
    @user = User.find(current_user.id)
    @subject = @user.subjects.find(params[:subject_id])
    @title = "#{@subject.name} Topics"
    @topics = @subject.topics.order("id")
  end

  def new
    @title = "New Topic"
    @user = User.find(current_user.id)
    @subject = @user.subjects.find(params[:subject_id])
    @topic = @subject.topics.new
  end

  def edit
    @title = "Edit Topic"
    @user = User.find(current_user.id)
    @subject = @user.subjects.find(params[:subject_id])
    @topic = @subject.topics.find(params[:id])
  end

  def create
    @topic = Topic.new(params[:topic])
    @topic.user_id = current_user.id
    respond_to do |format|
      if @topic.save
        format.html { redirect_to subject_topics_path(@topic.subject_id), notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @user = User.find(current_user.id)
    @subject = @user.subjects.find(params[:subject_id])
    @topic = @subject.topics.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to subject_topics_path(@topic.subject_id), notice: 'Topic was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @subject = @user.subjects.find(params[:subject_id])
    @topic = @subject.topics.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to subject_topics_url }
      format.json { head :no_content }
    end
  end

  private
 
  def require_login
    unless user_signed_in?
      redirect_to root_url, flash: { error: "You must be logged in to access this section"}
    end
  end

  def set_title
    @title = "Subjects"
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [@subject, @topic] do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :subject_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<%= render 'form' %>

<br>
<%= link_to "Back to Topics", subject_topics_path(@subject), class: "button" %>
<br>
<br>
<%= link_to "Delete Topic", [@subject, @topic], method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>

app/views/topics/index.html.erb
<%= link_to raw('&larr; Back to Subjects'), subjects_path, class: "button" %>
<br>
<br>
<% @topics.each do |topic| %>
    <span class="buttongroup3"><span class="button"><%= topic.name %></span><%= link_to 'View Notes', subject_topic_notes_path(@subject, topic), class: "button" %><%= link_to 'Edit', edit_subject_topic_path(@subject, topic), class: "button" %></span>
    <br>
    <br>
<% end %>
<%= link_to '+ New Topic', new_subject_topic_path(@subject), class: "button" %>

app/views/topics/new.html.erb
<%= render 'form' %>