config/routes.rb
Penpencilruler::Application.routes.draw do

  get '/terms' => 'pages#terms'
  get '/privacy' => 'pages#privacy'
  get '/copyright' => 'pages#copyright'
  get '/feedback' => 'pages#feedback'
  get '/cookies' => 'pages#cookies'
  get '/suspended' => 'pages#suspended', as: 'suspended'

  devise_for :users, controllers: { registrations: "users/registrations"}

  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    resource :registration,
    only: [:new, :create, :edit, :update],
    path: 'users',
    path_names: { new: 'sign_up' },
    controller: 'devise/registrations',
    as: :user_registration do
      get :cancel
    end
  end

  resources :search

  resources :subjects do
    resources :topics do
      resources :notes
    end
  end

  get '/admin' => 'admin#index', as: 'admin'
  get '/admin/users/search/:search' => 'admin#users', as: 'admin_userssearch'
  get '/admin/users(/:id)' => 'admin#users', as: 'admin_users'
  get '/admin/become/:id' => 'admin#become', as: 'admin_become'
  get '/admin/suspend/:id' => 'admin#suspend', as: 'admin_suspend'
  get '/admin/unsuspend/:id' => 'admin#unsuspend', as: 'admin_unsuspend'
  get '/admin/allowdeletion/:id' => 'admin#allowdeletion', as: 'admin_allowdeletion'
  get '/admin/preventdeletion/:id' => 'admin#preventdeletion', as: 'admin_preventdeletion'

  get '/admin/support' => redirect('https://secure.helpscout.net'), as: 'admin_support'
  get '/admin/newrelic' => redirect('https://rpm.newrelic.com'), as: 'admin_newrelic'
  get '/admin/postmarkapp' => redirect('https://postmarkapp.com'), as: 'admin_postmarkapp'

  root :to => 'pages#index'

end

app/views/admin/index.html.erb
<h1>Dashboard</h1>
<div class="row-fluid">
  <div class="span4"><h2><%= @newusercount %></h2> new users this week</div>
  <div class="span4"><h2><%= @activeusercount %></h2> active users this week</div>
  <div class="span4"><h2><%= @emailunconfirmedusercount %></h2> users who have not confirmed their email</div>
</div>
    

app/views/admin/users.html.erb
<h1>Users</h1>

<%= form_tag('/admin/users', :method => 'get', :class => "form-search") do %>
  <%= text_field "", :search, class: "input-medium search-query" %>
  <button type="submit" class="btn">Search</button>
<% end %>

<%# Show individual user %>

<% if !params[:id].nil? %>
  <h3><%= @user.name %>
    <% if @user.is_admin? %><span class='label label-success'>Admin</span><% end %>
    <% if @user.is_suspended? %><span class='label label-important'>Suspended</span><% end %>
    <% if !@user.confirmation_token.nil? %><span class='label label-info'>Unconfirmed</span><% end %>
    <% if @user.deletion_allowed? %><span class='label label-important'>Deletion Allowed</span><% end %>
  </h3>
  <p>Email: <%= @user.email %> (<%= "Confirmed at #{@user.confirmed_at}" if @user.confirmation_token.nil? %><%= "Unconfirmed - sent confirmation at #{@user.confirmation_sent_at}" if !@user.confirmation_token.nil? %>)</p>
  <p>Sign in count: <%= @user.sign_in_count %></p>
  <p>Current sign in: <%= @user.current_sign_in_at %> at <%= @user.current_sign_in_ip %></p>
  <p>Last sign in: <%= @user.last_sign_in_at %> at <%= @user.last_sign_in_ip %></p>
  <p>Account info: Created at <%= @user.created_at %> and updated at <%= @user.updated_at %></p>
  <p>User Id: <%= @user.id %></p>
  <p>Admin: <%= @user.is_admin %></p>
  <p>Suspended: <%= @user.is_suspended %><% if @user.is_suspended? %> by <%= User.find(@user.suspended_by).name %> (<%= User.find(@user.suspended_by).email %>)<% end %></p>
  <p>Deletion allowed: <%= @user.deletion_allowed %><% if @user.deletion_allowed? %> by <%= User.find(@user.deletion_by).name %> (<%= User.find(@user.deletion_by).email %>)<% end %></p>
  <% if !@user.is_admin? %>
    <%= link_to "Become user", admin_become_path(@user.id), :class => "btn btn-success" %>
    <% if @user.is_suspended? %>
      <%= link_to "Unsuspend user", admin_unsuspend_path(@user.id), :class => "btn btn-warning" %>
    <% else %>
      <%= link_to "Suspend user", admin_suspend_path(@user.id), :class => "btn btn-warning" %>
    <% end %>
    <% if @user.deletion_allowed? %>
      <%= link_to "Prevent deletion", admin_preventdeletion_path(@user.id), :class => "btn btn-danger" %>
    <% else %>
      <%= link_to "Allow deletion", admin_allowdeletion_path(@user.id), :class => "btn btn-danger" %>
    <% end %>
  <% end %>
<% end %>

<%# List users %>

<% if params[:id].nil? %>
  <ul>
    <% for user in @users %>
      <li><%= link_to "#{user.name} (#{user.email})", admin_users_path(user.id) %>
      <% if user.is_admin? %><span class='label label-success'>Admin</span><% end %>
      <% if user.is_suspended? %><span class='label label-important'>Suspended</span><% end %>
      <% if !user.confirmation_token.nil? %><span class='label label-info'>Unconfirmed</span><% end %>
      <% if user.deletion_allowed? %><span class='label label-important'>Deletion Allowed</span><% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<%# Paginate list of users %>

<% if params[:id].nil? %>
  <br>
  <%= paginate @users %>
<% end %>