config/routes.rb
Penpencilruler::Application.routes.draw do

  get '/terms' => 'pages#terms'
  get '/privacy' => 'pages#privacy'
  get '/copyright' => 'pages#copyright'
  get '/feedback' => 'pages#feedback'
  get '/cookies' => 'pages#cookies'
  get '/suspended' => 'pages#suspended', as: 'suspended'

  devise_for :users, controllers: { registrations: "users/registrations"}

  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    resource :registration,
    only: [:new, :create, :edit, :update],
    path: 'users',
    path_names: { new: 'sign_up' },
    controller: 'devise/registrations',
    as: :user_registration do
      get :cancel
    end
  end

  resources :search

  resources :subjects do
    resources :topics do
      resources :notes
    end
  end

  get '/admin' => 'admin#index', as: 'admin'
  get '/admin/users/search/:search' => 'admin#users', as: 'admin_userssearch'
  get '/admin/users(/:id)' => 'admin#users', as: 'admin_users'
  get '/admin/become/:id' => 'admin#become', as: 'admin_become'
  get '/admin/suspend/:id' => 'admin#suspend', as: 'admin_suspend'
  get '/admin/unsuspend/:id' => 'admin#unsuspend', as: 'admin_unsuspend'
  get '/admin/allowdeletion/:id' => 'admin#allowdeletion', as: 'admin_allowdeletion'
  get '/admin/preventdeletion/:id' => 'admin#preventdeletion', as: 'admin_preventdeletion'

  get '/admin/support' => redirect('https://secure.helpscout.net'), as: 'admin_support'
  get '/admin/newrelic' => redirect('https://rpm.newrelic.com'), as: 'admin_newrelic'
  get '/admin/postmarkapp' => redirect('https://postmarkapp.com'), as: 'admin_postmarkapp'

  root :to => 'pages#index'

end

app/views/pages/cookies.html.erb
<% @title = "Cookies Policy" %>
<p>Pen Pencil Ruler uses Google Analytics, which uses cookies, to track a visitor's usage of the Pen Pencil Ruler website and you may opt-out of this by setting your browser to refuse cookies before using this website.</p>
<p>Our Privacy Policy, which includes a section on this website's usage of cookies, can be found at <%= link_to privacy_url, privacy_path %></p>

app/views/pages/copyright.html.erb
<% @title = "Copyright Infringement Claims" %>
<p>Copyright infringement claims must be sent to <a href="mailto:support@penpencilruler.com">support@penpencilruler.com</a> and claims must be a written communication, including:</p> 
<ul>
  <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
  <li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single Notification, a representative list of such works.</li>
  <li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information sufficient to permit us to locate the material.</li>
  <li>Information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number and if available, an electronic mail address at which the complaining party may be contacted.</li>
  <li>A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</li>
  <li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
</ul>

app/views/pages/feedback.html.erb
<% @title = "Feedback" %>
<div class="main feedback">
  <div class="maxwidth">
    <article class="indexinfo30">
      <img class="hero" src="<%= image_path("iconmonstr-bug-3-icon.png") %>">
      <p>Report a bug</p>
      <p>Send an email to <a href="mailto:support@penpencilruler.com">support@penpencilruler.com</a> which includes how you came across this bug</p>
    </article>
    <article class="indexinfo30">
      <img class="hero" src="<%= image_path("iconmonstr-help-5-icon.png") %>">
      <p>Ask for help</p>
      <p>Ask us by emailing us at <a href="mailto:support@penpencilruler.com">support@penpencilruler.com</a></p>
    </article>
    <article class="indexinfo30">
      <img class="hero" src="<%= image_path("iconmonstr-light-bulb-17-icon.png") %>">
      <p>Have an idea?</p>
      <p>Email us at <a href="mailto:support@penpencilruler.com">support@penpencilruler.com</a></p>
    </article>
  </div>
</div>

app/views/pages/index.html.erb
<div class="main index">
  <div class="maxwidth">
    <a href="login" class="login">Login</a></p>
    <img class="hero" src="<%= image_path("hero.png") %>">
    <p class="subtitle center large">Studying made easier</p>
    <p class="center buttons"><a href="signup" class="signup large">Sign up for free</a>
    
    <article class="indexinfo30">
      <img class="hero" src="<%= image_path("iconmonstr-text-file-3-icon.png") %>">
      <p>Organise your notes into subjects and topics</p>
    </article>
    <article class="indexinfo30">
      <img class="hero" src="<%= image_path("iconmonstr-full-folder-icon.png") %>">
      <p>A central place to store your revision notes</p>
    </article>
    <article class="indexinfo30">
      <img class="hero" src="<%= image_path("iconmonstr-lock-3-icon.png") %>">
      <p>Your notes are private by default</p>
    </article>
  </div>
</div>

app/views/pages/privacy.html.erb
<% @title = "Privacy Policy" %>

<aside class="annotation">The following document is Pen Pencil Ruler's Privacy Policy. You should read this carefully before you use Pen Pencil Ruler. We have included annotations throughout this document which are not part of the policy, but they are to help you understand the policy.</aside>

<p>If you have questions about deleting or correcting your personal data please contact our support team at <a href="mailto:support@penpencilruler.com">support@penpencilruler.com</a>.</p>

<p>Jack Hughes ("We", "Us" or "Our") operates penpencilpaper.com. It is our policy to respect your privacy regarding any information we may collect while operating our websites.</p>

<p><h2>Website Visitors</h2>
Like most website operators, we collect non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Our purpose in collecting non-personally identifying information is to better understand how our visitors use its website. From time to time, we may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>

<span class="arrow"></span><aside class="annotation">We may collect non-personally-identifying information for analytics.</aside>

<p>We also collect potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users. We only disclose logged in user IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below.</p>

<p><h2>Gathering of Personally-Identifying Information</h2>
Certain visitors to this website (Pen Pencil Ruler) choose to interact with us in ways that require us to gather personally-identifying information. The amount and type of information that we gather depends on the nature of the interaction. For example, we ask visitors who sign up for an account at penpencilruler.com to provide their name and email address. Those who engage in transactions with us are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case, we collect such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor’s interaction with us. We do not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>

<span class="arrow"></span><aside class="annotation">Any personally-identifying information will not be disclosed and you may refuse to provide this information, however you may not be able to use certain parts of this website as a result.</aside>

<p><h2>Aggregated Statistics</h2>
We may collect statistics about the behaviour of visitors to its websites. For instance, we may monitor certain accounts. We may display this information publicly or provide it to others. However, we do not disclose personally-identifying information other than as described below.</p>

<span class="arrow"></span><aside class="annotation">We may monitor the behaviour of visitors.</aside>

<p><h2>Protection of Certain Personally-Identifying Information</h2>
We disclose potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on our behalf or to provide services available at our websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using our websites, you consent to the transfer of such information to them. We will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, we disclose potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when we believe in good faith that disclosure is reasonably necessary to protect the property or rights of us, third parties or the public at large. If you are a registered user of Pen Pencil Ruler and have supplied your email address, we may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with us and our products. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. We take all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>

<span class="arrow"></span><aside class="annotation">We will not disclose personally-identifying information unless needed by partners or the law. We may contact you using your email address.</aside>

<p><h2>Cookies</h2>
A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. We uses cookies to help us identify and track visitors, their usage of the Pen Pencil Ruler website, and their website access preferences. Visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using our websites, with the drawback that certain features of our websites may not function properly without the aid of cookies.</p>

<span class="arrow"></span><aside class="annotation">Pen Pencil Ruler uses cookies to track a visitor's usage of the Pen Pencil Ruler website and you may opt-out of this by setting your browser to refuse cookies before using this website.</aside>

<p><h2>Ads</h2>
Ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by us and does not cover the use of cookies by any advertisers.</p>

<span class="arrow"></span><aside class="annotation">Advertising partners may set cookies and this policy overs the use of cookies by us and not advertisers.</aside>

<p><h2>Privacy Policy Changes</h2>
Although most changes are likely to be minor, we may change our Privacy Policy from time to time, and in our sole discretion. We encourage visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</p>

<span class="arrow"></span><aside class="annotation">We may change our privacy policy at any time and you should check this policy from time to time. If you continue to use the website after changes, you agree to these changes.</aside>

<h2>Change log:</h2>

<ul>
  <li>August 24, 2013: First version</li>
</ul>

app/views/pages/suspended.html.erb
<% @title = "Suspended" %>
<div class="alert-message">
  <br>
  Your account has been suspended. Please contact <a href="mailto:support@penpencilruler.com">support@penpencilruler.com</a>.
  <br>
  &nbsp;
</div>

app/views/pages/terms.html.erb
<% @title = "Terms of Service" %>

<aside class="annotation">The following document is Pen Pencil Ruler's Terms of Service. You should read this carefully before you use Pen Pencil Ruler. We have included annotations throughout this document which are not part of the contract, but they are to help you understand the contract.</aside>

<p>By using "Pen Pencil Ruler", which refers to the "Service" on <a href="http://www.penpencilruler.com">www.penpencilruler.com</a> provided by Jack Hughes ("We" or "Us", contact email: <a href="mailto:jack@jackhughesweb.com">jack@jackhughesweb.com</a>), you are agreeing to be bound by the following terms and conditions ("Terms of Service").</p>

<span class="arrow"></span><aside class="annotation">Simply, you agree to the following Terms of Service.</aside>

<p>We reserve the right to update and change the Terms of Service from time to time without notice. Any new features that augment or enhance the current Service, including the release of new tools and resources, shall be subject to the Terms of Service. Continued use of the Service after any such changes shall constitute your consent to such changes. You can review the most current version of the Terms of Service at any time at: <%= link_to terms_url, terms_path %></p>

<span class="arrow"></span><aside class="annotation">We reserve the right to change these Terms of Service and it is up to you to check these regularly.</aside>

<p>Violation of any of the terms below will result in the suspension and termination of your Account. You understand and agree that we cannot be responsible for the Content posted on the Service and you nonetheless may be exposed to such materials. You agree to use the Service at your own risk.</p>

<span class="arrow"></span><aside class="annotation">If you break any of these terms, your account will be suspended or deleted. Also, Pen Pencil Ruler is not responsible for any content on the website and you use this service at your own risk.</aside>

<h2>Account Terms</h2>

<ol>
  <li>You must be 13 years or older to use this Service.</li>
  <li>You must be a human. Accounts registered by "bots" or other automated methods are not permitted.</li>
  <li>You must provide your legal full name, a valid email address, and any other information requested in order to signup.</li>
  <li>Your login may only be used by one person - a single login shared by multiple people is not permitted.</li>
  <li>You are responsible for maintaining the security of your account and password. We cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.</li>
  <li>You are responsible for all Content posted and activity that occurs under your account (even when Content is posted by others who have accounts under your account).</li>
  <li>You may not use the Service for any illegal or unauthorized purpose. You must not, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).</li>
</ol>

<h2>Cancellation and Termination</h2>

<ol>
  <li>You are solely responsible for properly cancelling your account. You can cancel your account at any time by:
    <ol>
      <li>Clicking on your name in the navigation bar at the top of the screen and clicking on "Edit Account" or by visiting <%= link_to edit_user_registration_url, edit_user_registration_path %></li>
      <li>In the section for cancelling your account, an email address is displayed and you must send an email to this address using your account email address to request an account deletion (this safety measure helps to reduce the likelihood of an unauthorised deletion of your account)</li>
      <li>When your request has been processed by us, visit the "Edit Account" page as above and click on the button to cancel your account. After accepting the confirmation dialog, your account will be deleted</li>
    </ol>
  </li>
  <li>All of your Content will be immediately deleted from the Service upon cancellation. This information can not be recovered once your account is cancelled.</li>        
  <li>We, in our sole discretion, have the right to suspend or terminate your account and refuse any and all current or future use of the Service, for any reason at any time. Such termination of the Service will result in the deactivation or deletion of your Account or your access to your Account, and the forfeiture and relinquishment of all Content in your Account. We reserve the right to refuse service to anyone for any reason at any time.</li>
</ol>

<span class="arrow"></span><aside class="annotation">You can delete your account by following the instructions above and this will delete all content on Pen Pencil Ruler. We have the right to suspend or terminate your account if you break these terms of service.</aside>

<h2>Modifications to the Service</h2>

<ol>
  <li>We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice.</li>
  <li>We shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</li>
</ol>

<span class="arrow"></span><aside class="annotation">Pen Pencil Ruler may shut down with or without notice and we are not liable for any changes or discontinuation of the service.</aside>

<h2>Copyright and Content Ownership</h2>

<ol>
  <li>All content posted on the Service is must comply with U.K. copyright law. Please <%= link_to 'review our copyright compliance policy.', copyright_path %></li>
  <li>We claim no intellectual property rights over the material you provide to the Service. Your profile and materials uploaded remain yours.</li>
  <li>We do not pre-screen Content, but we have the right (but not the obligation) in their sole discretion to refuse or remove any Content that is available via the Service.</li>
</ol>

<span class="arrow"></span><aside class="annotation">All content that you add to Pen Pencil Ruler is your content and we do not claim copyright over your content.</aside>

<h2>Technical support</h2>

<ol>
  <li>Technical support is only available via email at <a href="mailto:support@penpencilruler.com">support@penpencilruler.com</a>.</li>
</ol>

<h2>Terms</h2>

<ol>
  <li>Your use of the Service is at your sole risk. The service is provided on an "as is" and "as available" basis.</li>
  <li>You understand that we use third party vendors and hosting partners to provide the necessary hardware, software, networking, storage, and related technology required to run the Service.</li>
  <li>You must not modify, adapt or hack the Service or modify another website so as to falsely imply that it is associated with the Service or us.</li>
  <span class="arrow"></span><aside class="annotation">You must not create any publication which falsely implies that it is related to Pen Pencil Ruler.</aside>
  <li>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service without the express written permission by us.</li>
  <span class="arrow"></span><aside class="annotation">You must not reproduce, duplicate, copy, sell, resell or exploit Pen Pencil Paper</aside>
  <li>We may, but have no obligation to, remove Content and Accounts containing Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms of Service.</li>
  <span class="arrow"></span><aside class="annotation">We will remove inappropriate content.</aside>
  <li>Verbal, physical, written or other abuse (including threats of abuse or retribution) of any customer, employee, member, or officer will result in immediate account termination.</li>
  <span class="arrow"></span><aside class="annotation">Any abuse towards the Pen Pencil Ruler team will result in your account being suspended or terminated.</aside>
  <li>You understand that the technical processing and transmission of the Service, including your Content, may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</li>
  <span class="arrow"></span><aside class="annotation">You understand that your content may be transferred over an unencrypted internet connection.</aside>
  <li>You must not upload, post, host, or transmit unsolicited email, SMSs, or "spam" messages.</li>
  <li>You must not transmit any worms or viruses or any code of a destructive nature.</li>
  <span class="arrow"></span><aside class="annotation">Don't do anything inappropriate.</aside>
  <li>If your bandwidth usage significantly exceeds the average bandwidth usage (as determined solely by us) of other Pen Pencil Ruler customers, we reserve the right to immediately disable your account until you can reduce your bandwidth consumption.</li>
  <span class="arrow"></span><aside class="annotation">We may suspend your account if your usage is higher than average.</aside>
  <li>We do not warrant that (i) the service will meet your specific requirements, (ii) the service will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the service will be accurate or reliable, (iv) the quality of any products, services, information, or other material purchased or obtained by you through the service will meet your expectations, and (v) any errors in the Service will be corrected.</li>
  <span class="arrow"></span><aside class="annotation">Pen Pencil Ruler may not be perfect for you and it may not be error free but we will do our best to make Pen Pencil Ruler a great service.</aside>
  <li>You expressly understand and agree that we shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if we have been advised of the possibility of such damages), resulting from: (i) the use or the inability to use the service; (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the service; (iii) unauthorized access to or alteration of your transmissions or data; (iv) statements or conduct of any third party on the service; (v) or any other matter relating to the service.</li>
  <span class="arrow"></span><aside class="annotation">We are not liable for any losses and we recommend that you save a backup of your notes elsewhere.</aside>
  <li>The failure of us to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. The Terms of Service constitutes the entire agreement between you and us and govern your use of the Service, superceding any prior agreements between you and us (including, but not limited to, any prior versions of the Terms of Service).</li>
  <span class="arrow"></span><aside class="annotation">Even if we do not enforce this Terms of Service, this is not a waiver of these Terms.</aside>
  <li>Questions about the Terms of Service should be sent to <a href="mailto:support@penpencilruler.com">support@penpencilruler.com</a>.</li>
  <span class="arrow"></span><aside class="annotation">If you have any questions about these Terms, email us.</aside>
</ol>

<h2>Change log:</h2>

<ul>
  <li>August 24, 2013: First version</li>
</ul>