config/routes.rb
Penpencilruler::Application.routes.draw do

  get '/terms' => 'pages#terms'
  get '/privacy' => 'pages#privacy'
  get '/copyright' => 'pages#copyright'
  get '/feedback' => 'pages#feedback'
  get '/cookies' => 'pages#cookies'
  get '/suspended' => 'pages#suspended', as: 'suspended'

  devise_for :users, controllers: { registrations: "users/registrations"}

  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    resource :registration,
    only: [:new, :create, :edit, :update],
    path: 'users',
    path_names: { new: 'sign_up' },
    controller: 'devise/registrations',
    as: :user_registration do
      get :cancel
    end
  end

  resources :search

  resources :subjects do
    resources :topics do
      resources :notes
    end
  end

  get '/admin' => 'admin#index', as: 'admin'
  get '/admin/users/search/:search' => 'admin#users', as: 'admin_userssearch'
  get '/admin/users(/:id)' => 'admin#users', as: 'admin_users'
  get '/admin/become/:id' => 'admin#become', as: 'admin_become'
  get '/admin/suspend/:id' => 'admin#suspend', as: 'admin_suspend'
  get '/admin/unsuspend/:id' => 'admin#unsuspend', as: 'admin_unsuspend'
  get '/admin/allowdeletion/:id' => 'admin#allowdeletion', as: 'admin_allowdeletion'
  get '/admin/preventdeletion/:id' => 'admin#preventdeletion', as: 'admin_preventdeletion'

  get '/admin/support' => redirect('https://secure.helpscout.net'), as: 'admin_support'
  get '/admin/newrelic' => redirect('https://rpm.newrelic.com'), as: 'admin_newrelic'
  get '/admin/postmarkapp' => redirect('https://postmarkapp.com'), as: 'admin_postmarkapp'

  root :to => 'pages#index'

end

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pen Pencil Ruler - Studying made easier</title>
  <link rel="shortcut icon" href="<%= image_path('pencil.png') %>">
  <%= stylesheet_link_tag    "application-admin", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pen Pencil Ruler", root_path, :class => "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="<%= current_path(admin_path) %>"><%= link_to "Home", admin_path %></li>
          <li class="<%= current_path(admin_users_path) %>"><%= link_to "Users", admin_users_path %></li>
          <li class="<%= current_path(admin_support_path) %>"><%= link_to "Support", admin_support_path %></li>
          <li class="<%= current_path(admin_newrelic_path) %>"><%= link_to "New Relic", admin_newrelic_path %></li>
          <li class="<%= current_path(admin_postmarkapp_path) %>"><%= link_to "Postmark", admin_postmarkapp_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
     
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pen Pencil Ruler - Studying made easier</title>
  <link rel="shortcut icon" href="<%= image_path('pencil.png') %>">
  <link href='//fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application-main", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="maxwidth">
      <span class="userinfo"><% if user_signed_in? %><input type="checkbox" id="usertoggle"><span class="expand">
            <a href="<%= search_index_path %>" style="display: inline !important;"><img src="/assets/iconmonstr-magnifier-icon.png" height="20px" style="vertical-align: sub;"> Search</a>
            <label for="usertoggle"><%= current_user.name %></label>
            <%= link_to "Edit account", edit_user_registration_path %>
            <%= link_to "Sign out", logout_path %>
          </span>
        <% end %>
      </span>
      <a href="/" class="home"><img src="<%= image_path("pencil.png") %>" class="navlogo"></a>
      <span class="navcurrent"><%= @title %></span>
    </div>
  </header>
  <% [:notice, :error, :alert].each do |level| %>
    <% unless flash[level].blank? %>
      <div class="alert alert-<%= level == :notice ? "success" : "error" %>">
        <div class="main">
          <div class="maxwidth">
            <p>
              <span class="alert-close">X</span>
              <%= flash[level] %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="main">
  <div class="maxwidth">
<%= yield %>
</div>
</div>
<footer>
  <div class="maxwidth">
    <a href="http://www.jackhughesweb.com" class="hint--top hint--rounded" data-hint="Created by Jack Hughes (@jackhughesweb)"><img src="<%= image_path('jh.png') %>" width="25" height="25"></a>
    <br>
    <%= link_to "Terms of Service", terms_url %>
    -
    <%= link_to "Privacy Policy", privacy_url %>
    <br>
    <%= link_to "Cookies", cookies_url %>
    -
    <%= link_to "Feedback", feedback_url %>
    <br>
  </div>
</footer>
<% if Rails.env == 'production' %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44434861-1', 'penpencilruler.com');
    ga('send', 'pageview');

  </script>
<% end %>
</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pen Pencil Ruler - Studying made easier</title>
  <link rel="shortcut icon" href="<%= image_path('pencil.png') %>">
  <link href='//fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application-main", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% [:notice, :error, :alert].each do |level| %>
    <% unless flash[level].blank? %>
      <div class="alert alert-<%= level == :notice ? "success" : "error" %>">
        <div class="main">
          <div class="maxwidth">
            <p>
              <span class="alert-close">X</span>
              <%= flash[level] %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<%= yield %>
<footer>
  <div class="maxwidth">
    <a href="http://www.jackhughesweb.com" class="hint--top hint--rounded" data-hint="Created by Jack Hughes (@jackhughesweb)"><img src="<%= image_path('jh.png') %>" width="25" height="25"></a>
    <br>
    <%= link_to "Terms of Service", terms_url %>
    -
    <%= link_to "Privacy Policy", privacy_url %>
    <br>
    <%= link_to "Cookies", cookies_url %>
    -
    <%= link_to "Feedback", feedback_url %>
  </div>
</footer>
<% if Rails.env == 'production' %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44434861-1', 'penpencilruler.com');
    ga('send', 'pageview');

  </script>
<% end %>
</body>
</html>